insert into Coach(name, age, work_experience, country_id)
values ('pep guardiola', 45, 13, 1)
insert into Coach(name, age, work_experience, country_id)
values ('ronald koeman', 57, 15, 2)
insert into Coach(name, age, work_experience, country_id)
values ('valverde', 50, 17, 1)
insert into Coach(name, age, work_experience, country_id)
values ('zidane', 48, 6, 3)

insert into Country(name)
values ('spain')
insert into Country(name)
values ('netherland')
insert into Country(name)
values ('france')
insert into Country(name)
values ('Argentina')

insert into Reffree(name)
values('chaker')

insert into Stadium(name, capacity, city, country_id)
values('newcamp', 90000, 'barcelon', 1)
insert into Stadium(name, capacity, city, country_id)
values('santiago bernabeu', 60000, 'madrid', 1)
insert into Stadium(name, capacity, city, country_id)
values('johan cruyff arena', 45000, 'amesterdam', 2)


insert into Match(date, time, teams, weather, stadium_id, reffree_id)
values ('2021-01-03', '23:30:00', 'barcelona-real', 'rainy', 1, 1)
insert into Match(date, time, teams, weather, stadium_id, reffree_id)
values ('2021-01-02', '23:30:00', 'barcelona-ajax', 'sunny', 1, 1)

insert into Groups(name)
values('A')
insert into Groups(name)
values('B')


insert into Team(name, number_of_titles, is_eliminated, stadium_id, country_id, coach_id, group_id)
values ('barcelona', 5, 0, 1, 1, 2, 1)
insert into Team(name, number_of_titles, is_eliminated, stadium_id, country_id, coach_id, group_id)
values ('real madrid', 13, 0, 2, 1, 4, 1)
insert into Team(name, number_of_titles, is_eliminated, stadium_id, country_id, coach_id, group_id)
values ('ajax', 5, 0, 3, 2, 5, 1)

insert into Player(name, age, shirt_number, assists, saves, succesful_tackles, yellow_cards, red_cards, position, team_id, country_id)
values ('lionel messi', 32, 10, 6, 0, 2, 1, 0, 'forward', 1, 4)
insert into Player(name, age, shirt_number, assists, saves, succesful_tackles, yellow_cards, red_cards, position, team_id, country_id)
values ('sergio ramos', 34, 4, 0, 0, 12, 3, 0, 'deffender', 3, 1)
insert into Player(name, age, shirt_number, assists, saves, succesful_tackles, yellow_cards, red_cards, position, team_id, country_id)
values ('karim benzema', 31, 9, 2, 0, 1, 0, 1, 'forward', 3, 3)

insert into Goal(player_id, match_id, minute)
values(1, 3, 5)
insert into Goal(player_id, match_id, minute)
values(2, 3, 21)
insert into Goal(player_id, match_id, minute)
values(1, 3, 58)
insert into Goal(player_id, match_id, minute)
values(1, 3, 83)
insert into Goal(player_id, match_id, minute, ispenalty)
values(3, 3, 61, 1)
insert into Goal(player_id, match_id, minute, ispenalty)
values(3, 3, 92, 0)

insert into Plays_in(team_id, match_id, is_win, shoots)
values (1,3,'equal', 18)
insert into Plays_in(team_id, match_id, is_win, shoots)
values (3,3,'equal', 11)
insert into Plays_in(team_id, match_id, is_win, shoots)
values (1,4,'won', 15)
insert into Plays_in(team_id, match_id, is_win, shoots)
values (5,4,'lost', 2)
